#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Example.Resource", IsApplication=true)]

namespace Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::library.Resource.Drawable.border = global::Example.Resource.Drawable.border;
			global::library.Resource.Drawable.border_focused = global::Example.Resource.Drawable.border_focused;
			global::library.Resource.Drawable.close = global::Example.Resource.Drawable.close;
			global::library.Resource.Drawable.corner = global::Example.Resource.Drawable.corner;
			global::library.Resource.Drawable.hide = global::Example.Resource.Drawable.hide;
			global::library.Resource.Drawable.maximize = global::Example.Resource.Drawable.maximize;
			global::library.Resource.Id.body = global::Example.Resource.Id.body;
			global::library.Resource.Id.close = global::Example.Resource.Id.close;
			global::library.Resource.Id.content = global::Example.Resource.Id.content;
			global::library.Resource.Id.corner = global::Example.Resource.Id.corner;
			global::library.Resource.Id.description = global::Example.Resource.Id.description;
			global::library.Resource.Id.hide = global::Example.Resource.Id.hide;
			global::library.Resource.Id.icon = global::Example.Resource.Id.icon;
			global::library.Resource.Id.maximize = global::Example.Resource.Id.maximize;
			global::library.Resource.Id.title = global::Example.Resource.Id.title;
			global::library.Resource.Id.titlebar = global::Example.Resource.Id.titlebar;
			global::library.Resource.Id.window_icon = global::Example.Resource.Id.window_icon;
			global::library.Resource.Layout.drop_down_list_item = global::Example.Resource.Layout.drop_down_list_item;
			global::library.Resource.Layout.system_window_decorators = global::Example.Resource.Layout.system_window_decorators;
			global::library.Resource.String.close = global::Example.Resource.String.close;
			global::library.Resource.String.corner = global::Example.Resource.String.corner;
			global::library.Resource.String.hide = global::Example.Resource.String.hide;
			global::library.Resource.String.maximize = global::Example.Resource.String.maximize;
			global::library.Resource.String.window_icon = global::Example.Resource.String.window_icon;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int close = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int corner = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hide = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int maximize = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int View01 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int View02 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int background = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int body = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int button = 2131099669;
			
			// aapt resource value: 0x7f06000f
			public const int close = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int content = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int corner = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int description = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int edit = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int edit2 = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int hide = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int icon = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int id = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int maximize = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int status = 2131099666;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView2 = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int title = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int titlebar = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int view1 = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int window_icon = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int body = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int drop_down_list_item = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int simple = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int system_window_decorators = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int widgets = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int app_name = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int close = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int corner = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int hello = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int hide = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int maximize = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int window_icon = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
